app = 'rugby-anthem-backend'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1   # changed from 0 to avoid zero-machine state

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1